{{ if .Values.rclonepremiumize.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-premiumize.{{ .Values.dns_domain }}
spec:
  entryPoints:
  - websecure
  routes:
    - match: Host(`{{ .Release.Name }}-premiumize.{{ .Values.dns_domain }}`)
      kind: Rule
      services:
        - name: premiumize
          kind: Service
          port: 9999
      middlewares:  
        - name: {{ .Release.Name }}-traefik-forward-auth
{{ end }}