{{ if .Values.rclonetorbox.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-torbox.{{ .Values.dns_domain }}
spec:
  entryPoints:
  - websecure
  routes:
    - match: Host(`{{ .Release.Name }}-torbox.{{ .Values.dns_domain }}`)
      kind: Rule
      services:
        - name: torbox
          kind: Service
          port: 9999
      middlewares:  
        - name: {{ .Release.Name }}-traefik-forward-auth
{{ end }}