{{ if .Values.channelsdvr.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-channelsdvr.{{ .Values.dns_domain }}
spec:
  entryPoints:
  - websecure
  routes:
    - match: Host(`{{ .Release.Name }}-channelsdvr.{{ .Values.dns_domain }}`)
      kind: Rule
      services:
        - name: channelsdvr
          kind: Service
          port: 8089
      middlewares:  
        - name: {{ .Release.Name }}-add-x-dvr-forceauth
{{ end }}