{{ if .Values.rclonedebridlink.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-debridlink.{{ .Values.dns_domain }}
spec:
  entryPoints:
  - websecure
  routes:
    - match: Host(`{{ .Release.Name }}-debridlink.{{ .Values.dns_domain }}`)
      kind: Rule
      services:
        - name: debridlink
          kind: Service
          port: 8080
      middlewares:  
        - name: {{ .Release.Name }}-traefik-forward-auth
{{ end }}