{{ if .Values.rclonepremiumize.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: premiumize-config
data:
  rclone-debrid-provider.conf: |
    [debrid-provider]
    type = webdav
    url = https://webdav.premiumize.me/
    vendor = other
    user = REPLACEUSER
    pass = REPLACEPASS
# the password is not used by AD, it's the obscured version of "immaterial". All that matters is the API key, which is passed as a user var in an env var
{{ end }}
