{{ if .Values.rclonetorbox.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: torbox-config
data:
  rclone-debrid-provider.conf: |
    [debrid-provider]
    type = webdav
    url = https://webdav.torbox.app/
    user = REPLACEUSER
    pass = REPLACEPASS
    vendor = other
{{ end }}
