{{ if .Values.rclonedebridlink.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: debridlink
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rclone
  selector:
    matchLabels:
      name: rclone-{{ .Release.Name }}-debridlink
{{ end }}