{{ if .Values.rclonepremiumize.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "permit-csi-nodeplugin-rclone-ingress-premiumize"
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: rclonepremiumize
  ingress:
  # - fromEndpoints:
  #   - matchLabels:
  #       k8s:io.kubernetes.pod.namespace: csi-rclone
  #       app: csi-nodeplugin-rclone
  - toPorts:
      - ports:
        - port: '9999'
          protocol: TCP
{{ end }}
